on:
  push:
    branches:
      - main

jobs:
  sample:
    runs-on: ubuntu-latest
    name: Sample
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get PR labels
        id: pr-labels
        uses: irby/get-labels-on-push@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          env | grep GITHUB_PR_LABEL || true
